spring:
  kafka:
    username: sysadmin
    password: Newdt@123
#    bootstrap-servers: 10.2.104.143:31171,10.2.104.143:31172,10.2.104.143:31173  #bootstrap-servers：连接kafka的地址，多个地址用逗号分隔
    bootstrap-servers: 192.168.12.70:30005,192.168.12.70:30021,192.168.12.70:30020  #bootstrap-servers：连接kafka的地址，多个地址用逗号分隔
    consumer:
      group-id: myGroup
      enable-auto-commit: true
      auto-commit-interval: 100ms
      properties:
        session.timeout.ms: 15000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    jaas:
      enabled: true
    producer:
      retries: 0 #若设置大于0的值，客户端会将发送失败的记录重新发送
      batch-size: 16384 #当将多个记录被发送到同一个分区时， Producer 将尝试将记录组合到更少的请求中。这有助于提升客户端和服务器端的性能。这个配置控制一个批次的默认大小（以字节为单位）。16384是缺省的配置
      buffer-memory: 33554432 #Producer 用来缓冲等待被发送到服务器的记录的总字节数，33554432是缺省配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #关键字的序列化类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #值的序列化类
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="sysadmin" password="Newdt@123";'

#spring:
#  port: 8081
#  kafka:
#    consumer:
#      group-id: myGroup
#      enable-auto-commit: true
#      auto-commit-interval: 100ms
#      properties:
#        session.timeout.ms: 15000
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: earliest
##    properties:
##      security:
##        protocol: SASL_PLAINTEXT
##      sasl:
##        mechanism: PLAIN
##        jaas:
##          config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="houjun" password="Admin123";'
#    jaas:
#      enabled: true
#    bootstrap-servers:
#    - '192.168.12.76:30097'
#    - '192.168.12.76:30096'
#    - '192.168.12.76:30095'

