spring:
  redis:
#    主从模式 https://github.com/redisson/redisson/wiki/2.-Configuration#252-replicated-yaml-config-format
#    redisson:
#      config: |
#        replicatedServersConfig:
#          nodeAddresses:
#          - "redis://192.168.1.73:32010"
#          - "redis://192.168.1.73:32011"
#          - "redis://192.168.1.73:32012"

#   哨兵模式 https://github.com/redisson/redisson/wiki/2.-Configuration#272-sentinel-yaml-config-format
#    redisson:
#      config: |
#        sentinelServersConfig:
#          checkSentinelsList: false
#          sentinelsDiscovery: false
#          masterName: hj-ha-direct1651
#          sentinelAddresses:
#          - "redis://192.168.1.73:32254"

#    集群模式 https://github.com/redisson/redisson/wiki/2.-Configuration#242-cluster-yaml-config-format
    redisson:
      config: |
        clusterServersConfig:
          nodeAddresses:
          - "redis://192.168.1.73:32018"
          - "redis://192.168.1.73:32019"
