spring:
  redis:
    #    cluster:
    #      nodes:
    #      - 192.123.123.123
    #      - 192.123.123.23
    #      - 192.123.123.232
    sentinel:
      master: hj-ha-old2043
      nodes:
        - 192.168.1.73:32254
        - 192.168.1.70:32254
        - 192.168.1.72:32254

management:
  health:
    redis:
      enabled: false
