spring:
  redis:
    host: 192.168.1.73
    port: 31666
    password: Admin123
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

management:
  health:
    redis:
      enabled: false
