spring:
  redis:
    cluster:
      nodes:
      - 192.168.1.73:31666
    password: Admin123
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

management:
  health:
    redis:
      enabled: false
